name = "hugo-webslides"
license = "MIT"
licenselink = "https://github.com/RCjacH/hugo-webslides/blob/master/LICENSE.md"
description = "Hugo-WebSlides - Writing beautiful slides in markdown with Hugo."
homepage = "http://example.com/"
tags = ["slide", "presentation", "responsive", "landing page"]
features = ["webslides.js", "pre-made template", "shortcodes"]
min_version = 0.56

[author]
  name = "RCJacH"
  homepage = "https://RCJacH.github.io"

[original]
  name = "webslides.js"
  homepage = "https://webslides.tv/"
  repo = "https://github.com/webslides/WebSlides"
