baseURL = "https://github.com/rcjach/hugo-webslides.git"
languageCode = "en-us"
title = "A Hugo theme for creating Webslides.js presentations"
disableKinds = ["sitemap", "RSS"]
theme = "hugo-webslides"
themesDir = "../.."
tags = ["slide", "presentation", "responsive", "landing page"]
features = ["webslides.js", "pre-made template", "shortcodes"]

[params]
  author = "RCJacH"
  homepage = "RCJacH.github.io"


[params.webslides]
  banner = false
  slideshow = true
  vertical = false
  autoslide = false
  changeOnClick = false
  disableLoop = false
  minWheelDelta = 40
  disableNavigateOnScroll = false
  scrollWait = 450
  slideOffset = 50
  hideIndex = false

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true